	<div id="blueBox">
		<div id="logos">
			<a href="http://www.respecteurope.com"><img src="images/logos/respect_97x30.jpg" alt="Respect Europe" width="97" height="30" /></a>
			<a href="http://globe-europe.net"><img src="images/logos/globe_85x30.jpg" alt="Globe Europe" width="85" height="30" /></a>
			<a href="http://www.clubmadrid.org"><img src="images/logos/club_78x30.jpg" alt="Club De Madrid" width="78" height="30" /></a>				
		</div>
		<a href="?"><img src="images/system/road_to_copenhagen.jpg" alt="The Roadmap To Copenhagen" /></a>
	</div>
