		<div id="bookmarkRss">

			<!-- =================================== -->

			<script type="text/javascript">
				addthis_url    = location.href;
				addthis_title  = document.title;
				addthis_pub    = "copenhagen";
			</script>

			<script type="text/javascript" src="http://s7.addthis.com/js/addthis_widget.php?v=12" ></script>
			<a onmouseover="TagToTip('bookmarkHelp')" class="help"><img src="images/system/help.gif" alt="help" /></a>

			<div id="bookmarkHelp" style="display:none;">
				<h2 style="margin: 0;">Why is social bookmarking useful?</h2>
				<p>Social bookmarking is an online service which allows you to save and<br />
				categorize website pages by tagging them with keywords and share them with<br />
				others.</p>

				<p>It enables you to refer to your bookmarks in the future and view the<br />
				bookmarks of other people with similar interests.</p>
			</div>

			<!-- =================================== -->

			<a href="?c=rss"><img src="images/buttons/button_rss.jpg" style="border: 0;" alt="rss feeds" /></a>
			<a onmouseover="TagToTip('rssHelp')" class="help"><img src="images/system/help.gif" alt="help" /></a>

			<div id="rssHelp" style="display:none;">
				<h2 style="margin:0">Why is a RSS feed useful for me?</h2>
				<p>Subscribing to a RSS feed automatically keeps you up to date with newly<br />
				added content and enables you to choose when to check it. It is quicker<br />
				than revisiting the web page all the time and avoids you ever receiving<br />
				any emails alerting you of new content.</p>

				<p>You need software called a "news reader" to subscribe to an RSS feed.<br />
				Most internet browsers will have a news reader already installed but if<br />
				yours does not then you will need to choose one that will work with your<br />
				computer.</p>

				<p>When you click on the RSS button you can subscribe to the feed in<br />
				various ways, including by dragging the URL of the new feed into your news<br />
				reader or by cutting and pasting the URL as a new feed in your news<br />
				reader.</p>
			</div>
		</div>