<?php

$content = '
<h1>Registration Recieved - One Last Step</h1>
<p>Please check your inbox for an email from '.SITE_TITLE.'<br />
Remember that it could be in your spam folder.  The sender will be '.FROM_EMAIL.'<br />
Please click on the link or copy it into your browser to validate your account.</p>
<p><a href="?c=users&amp;a=resend_validation">Click Here</a> to resend the validation email.</p>';

?>
